// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYyqd7J9r2eAkr8QF3yMxgN0AUKP4DtE',
    appId: '1:64700451431:web:55a13988f76bdd7e0522c2',
    messagingSenderId: '64700451431',
    projectId: 'frameworkmobile-34954',
    authDomain: 'frameworkmobile-34954.firebaseapp.com',
    storageBucket: 'frameworkmobile-34954.firebasestorage.app',
    measurementId: 'G-CER9X0KZ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhjcnABVBaqRVEi1DUg4iKlsggbBVR0b8',
    appId: '1:64700451431:android:59234e9c51bea4c70522c2',
    messagingSenderId: '64700451431',
    projectId: 'frameworkmobile-34954',
    storageBucket: 'frameworkmobile-34954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRjhuA0KzkTxrQrAxbfsJmJGHnhMGwhU',
    appId: '1:64700451431:ios:c0ed9cc7c56acaab0522c2',
    messagingSenderId: '64700451431',
    projectId: 'frameworkmobile-34954',
    storageBucket: 'frameworkmobile-34954.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWRjhuA0KzkTxrQrAxbfsJmJGHnhMGwhU',
    appId: '1:64700451431:ios:c0ed9cc7c56acaab0522c2',
    messagingSenderId: '64700451431',
    projectId: 'frameworkmobile-34954',
    storageBucket: 'frameworkmobile-34954.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALYyqd7J9r2eAkr8QF3yMxgN0AUKP4DtE',
    appId: '1:64700451431:web:fbaf9d9bb8d89b580522c2',
    messagingSenderId: '64700451431',
    projectId: 'frameworkmobile-34954',
    authDomain: 'frameworkmobile-34954.firebaseapp.com',
    storageBucket: 'frameworkmobile-34954.firebasestorage.app',
    measurementId: 'G-9BX6Z6QXZ0',
  );
}
